build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\projects\utf8
branches:
  except:
    - gh-pages

install:
  - cinst -y curl
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y php
  - cd C:\tools\php\ext
  - curl -O http://xdebug.org/files/php_xdebug-2.3.2-5.6-vc11-nts-x86_64.dll
  - cd C:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_xdebug-2.3.2-5.6-vc11-x86_64.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\projects\utf8
  - mkdir build\logs
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist --no-interaction
  - php composer.phar dump-autoload -o

test_script:
  - cd C:\projects\utf8
  - php.exe --version
  - dir
  - vendor\bin\phpunit.bat
  - vendor\bin\coveralls.bat